FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Descargar recursos de NLTK
RUN python -c "import nltk; nltk.download('punkt')"

COPY app.py .

EXPOSE 8000

CMD ["python", "app.py"]
